# for registration
###
POST http://localhost:3001/api/auth/register 
Content-Type: application/json

{
    "username": "madara",
    "password": "beans/rice",
    "email": "amaditochukwu11@gmail.com"

}

###
#for verifying email

POST http://localhost:3001/api/auth/verify-email 
Content-Type: application/json

{
    "code": "709617"
}

###
#for logging user out

POST http://localhost:3001/api/auth/logout

# for logging in the user
###
POST http://localhost:3001/api/auth/login 
Content-Type: application/json

{
  "email": "amaditochukwu11@gmail.com",
  "password": "beans/rice"
}

###
#for forgort password testing

POST http://localhost:3001/api/auth/forgot-password 
Content-Type: application/json

{
  "email": "amaditochukwu11@gmail.com"
}


###
#for forgot email sussecss

POST http://localhost:3001/api/auth/reset-password/23c62f572b4892d7d7d95f10a3d75409bea2c3d4 
Content-Type: application/json

{
  "password": "tochi.123eo"
}



###

GET  http://localhost:3001/api/auth/check-auth


###

POST http://localhost:3001/api/auth/profile 
Content-Type: application/json

{
    "user": "66bc2b3dfae52cd8e3c8b8c9",
    "faculty": "Engineering",
  "department": "Computer Engineering",
  "regNumber": "TCH2025999",
  "gender": "Male",
  "currentLevel": "200level",
  "fullName": "amadi sixtus tochukwu",
  "email": "amaditochukwu11@gmail.com"
}

###
GET http://localhost:3001/api/auth/profile/66bc2b3dfae52cd8e3c8b8c9


###


PUT http://localhost:3001/api/auth/profile/66bc2b3dfae52cd8e3c8b8c9
Content-Type: application/json

{
  "faculty": "Engineering",
  "department": "Computer Engineering",
  "regNumber": "TCH2025999",
  "gender": "Male",
  "currentLevel": "200level",
  "fullName": "amadi sixtus tochukwu",
  "email": "amaditochukwu11@gmail.com"
}


###
POST http://localhost:3001/api/auth/gpa/save
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4OGE4MTdjNjgxNGI2NWUyYWUyZjFiZCIsImlhdCI6MTc1MzkwODY2NCwiZXhwIjoxNzUzOTEyMjY0fQ.-6TCCzSyrWQZPPWVmJPDREcNVJcFA0FZNTLj3_EN55Q

{
  "cgpa": 4.5,
  "courses": [
    {
      "code": "CSC 121",
      "unit": 2,
      "grade": "B"
    },
    {
      "code": "MTH 101",
      "unit": 3,
      "grade": "A"
    }
  ],
  "level": "200",
  "semester": "first",
  "year": 2023
}

###
# for get request

GET http://localhost:3001/api/auth/gpa/results
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4OGE4MTdjNjgxNGI2NWUyYWUyZjFiZCIsImlhdCI6MTc1MzkwODY2NCwiZXhwIjoxNzUzOTEyMjY0fQ.-6TCCzSyrWQZPPWVmJPDREcNVJcFA0FZNTLj3_EN55Q



### for getting by id

GET http://localhost:3001/api/auth/gpa/results/688a879c26a5313198075261
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4OGE4MTdjNjgxNGI2NWUyYWUyZjFiZCIsImlhdCI6MTc1MzkwODY2NCwiZXhwIjoxNzUzOTEyMjY0fQ.-6TCCzSyrWQZPPWVmJPDREcNVJcFA0FZNTLj3_EN55Q


### for delete

DELETE  http://localhost:3001/api/auth/gpa/results/688a879c26a5313198075261
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4OGE4MTdjNjgxNGI2NWUyYWUyZjFiZCIsImlhdCI6MTc1MzkwODY2NCwiZXhwIjoxNzUzOTEyMjY0fQ.-6TCCzSyrWQZPPWVmJPDREcNVJcFA0FZNTLj3_EN55Q
