# for registration
###
POST http://localhost:3001/api/auth/register 
Content-Type: application/json

{
    "username": "madara",
    "password": "beans/rice",
    "email": "dexsteroxy.1234@gmail.com"

}

###
#for verifying email

POST http://localhost:3001/api/auth/verify-email 
Content-Type: application/json

{
    "code": "709617"
}

###
#for logging user out

POST http://localhost:3001/api/auth/logout

# for logging in the user
###
POST http://localhost:3001/api/auth/login 
Content-Type: application/json

{
  "email": "amaditochukwu11@gmail.com",
  "password": "1234567"
}

###
#for forgort password testing

POST http://localhost:3001/api/auth/forgot-password 
Content-Type: application/json

{
  "email": "amaditochukwu11@gmail.com"
}


###
#for forgot email sussecss

POST http://localhost:3001/api/auth/reset-password/23c62f572b4892d7d7d95f10a3d75409bea2c3d4 
Content-Type: application/json

{
  "password": "tochi.123eo"
}



###

GET  http://localhost:3001/api/auth/check-auth


###

POST http://localhost:3001/api/auth/profile 
Content-Type: application/json

{
    "user": "66bc2b3dfae52cd8e3c8b8c9",
     "faculty": "physical science",
      "department": "mathematics",
       "regNumber": "toc20202020hi",
        "gender": "Male",
        "state": "imo state"
}

###
GET http://localhost:3001/api/auth/profile/66bc2b3dfae52cd8e3c8b8c9


###


PUT http://localhost:3001/api/auth/profile/66bc2b3dfae52cd8e3c8b8c9
Content-Type: application/json

{
  "faculty": "Engineering",
  "department": "Computer Engineering",
  "regNumber": "TCH2025999",
  "gender": "Male",
  "state": "Lagos"
}